      SUBROUTINE READCNTL(CNTRFL,NX,NY,LUH,LTR,UH_INTERN,UH_TRANS,
     &     RUNOFF_INTERN,RUNOFF_TRANS,ORDER,ORDER_N)

      IMPLICIT NONE

C     READS A CONTROL FILE AND INPUT PARAMETERS FOR ROUTING MODEL

      INTEGER NX
      INTEGER NY
      INTEGER LUH
      INTEGER LTR

      CHARACTER*11 CNTRFL

      INTEGER ORDER(4,NX*NY)

      REAL UH_INTERN(LUH,NX,NY)
      REAL UH_TRANS(LTR,NX,NY)
      REAL RUNOFF_INTERN(LUH,NX,NY)
      REAL RUNOFF_TRANS(LTR,NX,NY)

      INTEGER NREAD, ORDER_N, I

      NREAD = 21
      OPEN (UNIT=NREAD, FILE=CNTRFL, STATUS='OLD',
     &     FORM='FORMATTED')

      CALL read_real_spatial(NREAD,LUH,NX,NY,UH_INTERN)
      CALL read_real_spatial(NREAD,LTR,NX,NY,UH_TRANS)
      CALL read_real_spatial(NREAD,LUH,NX,NY,RUNOFF_INTERN)
      CALL read_real_spatial(NREAD,LTR,NX,NY,RUNOFF_TRANS)
      CALL read_int_spatial(NREAD,4,NX*NY,1,ORDER)

      DO I = 1, NX*NY
         IF (ORDER(1,I) .EQ. 0) THEN
            ORDER_N = I - 1
            EXIT
         END IF
      END DO

      END
