!=========================================================================
!  LDASLDASLDASLDASLDASLDASLDASLDASLDASLDAS  A U.S. Continental-Scale
!  D                                      L  Land Modeling and Data
!  A  --LAND DATA ASSIMILATION SCHEMES--  D  Assimilation Project.
!  S                                      A  This is the GSFC-LDAS Code.
!  LDASLDASLDASLDASLDASLDASLDASLDASLDASLDAS  http://ldas.gsfc.nasa.gov
!
!   GSFC - NCEP - OH - Princeton - Washington - Rutgers
!
!========================================================================= 
! setcatp.f:
!
! DESCRIPTION:
!  This subroutine retrieves CATCHMENT parameters - Significant F90 
!  revisions below this subroutine will be requiret in the future.
!
! REVISION HISTORY:
!  4 Apr 2000: Jeffrey Walker; Initial Code
!=========================================================================

      SUBROUTINE SETCATP(LDAS,CAT)

      USE ldas_module      ! LDAS non-model-specific 1-D variables
      USE cat_module       ! Catchment model variables
      IMPLICIT NONE
      type (ldasdec) LDAS
      type (catdec)  CAT(LDAS%NCATM)

!  Variables =====================================================
      INTEGER :: NCATM
      INTEGER, pointer :: VEGCLSLU(:)
      REAL, pointer :: DPTHLU(:),POROSLU(:),BF1LU(:),BF2LU(:),BF3LU(:)
      REAL, pointer :: ARS1LU(:),ARS2LU(:),ARS3LU(:),ARA1LU(:),ARA2LU(:)
      REAL, pointer :: ARA3LU(:),ARA4LU(:),ARW1LU(:),ARW2LU(:),ARW3LU(:)
      REAL, pointer :: ARW4LU(:),TSA1LU(:),TSA2LU(:),TSB1LU(:),TSB2LU(:)
      REAL, pointer :: GREENLU1(:),GREENLU2(:),GREENLU3(:),GREENLU4(:)
      REAL, pointer :: GREENLU5(:),GREENLU6(:),GREENLU7(:),GREENLU8(:)
      REAL, pointer :: GREENLU9(:),GREENLU10(:),GREENLU11(:)
      REAL, pointer :: GREENLU12(:),LAILU1(:),LAILU2(:),LAILU3(:)
      REAL, pointer :: LAILU4(:),LAILU5(:),LAILU6(:),LAILU7(:),LAILU8(:)
      REAL, pointer :: LAILU9(:),LAILU10(:),LAILU11(:),LAILU12(:)
      REAL, pointer :: ZOLLU1(:),ZOLLU2(:),ZOLLU3(:),ZOLLU4(:),ZOLLU5(:)
      REAL, pointer :: ZOLLU6(:),ZOLLU7(:),ZOLLU8(:),ZOLLU9(:)
      REAL, pointer :: ZOLLU10(:),ZOLLU11(:),ZOLLU12(:)
      REAL, pointer :: ALBEDOLU1(:),ALBEDOLU2(:),ALBEDOLU3(:)
      REAL, pointer :: ALBEDOLU4(:),ALBEDOLU5(:),ALBEDOLU6(:)
      REAL, pointer :: ALBEDOLU7(:),ALBEDOLU8(:),ALBEDOLU9(:)
      REAL, pointer :: ALBEDOLU10(:),ALBEDOLU11(:),ALBEDOLU12(:)
      REAL, pointer :: VGDLU1(:),VGDLU2(:),VGDLU3(:),VGDLU4(:),VGDLU5(:)
      REAL, pointer :: VGDLU6(:),VGDLU7(:),VGDLU8(:),VGDLU9(:)
      REAL, pointer :: VGDLU10(:),VGDLU11(:),VGDLU12(:) 
      CHARACTER*100 :: FILENAME

!=== End Variable Definition =============================================

!=== Allocate Space to Scratch Variables =================================
      FILENAME=LDAS%CAT_SFILE(1:index(LDAS%CAT_SFILE,' ')-1)//
     &         '/catchment.def'
      OPEN (10,FILE=FILENAME,FORM='FORMATTED',STATUS='OLD')
      READ (10,*) LDAS%NCAT
      CLOSE (10,STATUS='KEEP')
      ALLOCATE (VEGCLSLU(LDAS%NCAT))
      ALLOCATE (DPTHLU(LDAS%NCAT))
      ALLOCATE (POROSLU(LDAS%NCAT))
      ALLOCATE (BF1LU(LDAS%NCAT))
      ALLOCATE (BF2LU(LDAS%NCAT))
      ALLOCATE (BF3LU(LDAS%NCAT))
      ALLOCATE (ARS1LU(LDAS%NCAT))
      ALLOCATE (ARS2LU(LDAS%NCAT))
      ALLOCATE (ARS3LU(LDAS%NCAT))
      ALLOCATE (ARA1LU(LDAS%NCAT))
      ALLOCATE (ARA2LU(LDAS%NCAT))
      ALLOCATE (ARA3LU(LDAS%NCAT))
      ALLOCATE (ARA4LU(LDAS%NCAT))
      ALLOCATE (ARW1LU(LDAS%NCAT))
      ALLOCATE (ARW2LU(LDAS%NCAT))
      ALLOCATE (ARW3LU(LDAS%NCAT))
      ALLOCATE (ARW4LU(LDAS%NCAT))
      ALLOCATE (TSA1LU(LDAS%NCAT))
      ALLOCATE (TSA2LU(LDAS%NCAT))
      ALLOCATE (TSB1LU(LDAS%NCAT))
      ALLOCATE (TSB2LU(LDAS%NCAT))
      ALLOCATE (GREENLU1(LDAS%NCAT))
      ALLOCATE (GREENLU2(LDAS%NCAT))
      ALLOCATE (GREENLU3(LDAS%NCAT))
      ALLOCATE (GREENLU4(LDAS%NCAT))
      ALLOCATE (GREENLU5(LDAS%NCAT))
      ALLOCATE (GREENLU6(LDAS%NCAT))
      ALLOCATE (GREENLU7(LDAS%NCAT))
      ALLOCATE (GREENLU8(LDAS%NCAT))
      ALLOCATE (GREENLU9(LDAS%NCAT))
      ALLOCATE (GREENLU10(LDAS%NCAT))
      ALLOCATE (GREENLU11(LDAS%NCAT))
      ALLOCATE (GREENLU12(LDAS%NCAT))
      ALLOCATE (LAILU1(LDAS%NCAT))
      ALLOCATE (LAILU2(LDAS%NCAT))
      ALLOCATE (LAILU3(LDAS%NCAT))
      ALLOCATE (LAILU4(LDAS%NCAT))
      ALLOCATE (LAILU5(LDAS%NCAT))
      ALLOCATE (LAILU6(LDAS%NCAT))
      ALLOCATE (LAILU7(LDAS%NCAT))
      ALLOCATE (LAILU8(LDAS%NCAT))
      ALLOCATE (LAILU9(LDAS%NCAT))
      ALLOCATE (LAILU10(LDAS%NCAT))
      ALLOCATE (LAILU11(LDAS%NCAT))
      ALLOCATE (LAILU12(LDAS%NCAT))
      ALLOCATE (ZOLLU1(LDAS%NCAT))
      ALLOCATE (ZOLLU2(LDAS%NCAT))
      ALLOCATE (ZOLLU3(LDAS%NCAT))
      ALLOCATE (ZOLLU4(LDAS%NCAT))
      ALLOCATE (ZOLLU5(LDAS%NCAT))
      ALLOCATE (ZOLLU6(LDAS%NCAT))
      ALLOCATE (ZOLLU7(LDAS%NCAT))
      ALLOCATE (ZOLLU8(LDAS%NCAT))
      ALLOCATE (ZOLLU9(LDAS%NCAT))
      ALLOCATE (ZOLLU10(LDAS%NCAT))
      ALLOCATE (ZOLLU11(LDAS%NCAT))
      ALLOCATE (ZOLLU12(LDAS%NCAT))
      ALLOCATE (ALBEDOLU1(LDAS%NCAT))
      ALLOCATE (ALBEDOLU2(LDAS%NCAT))
      ALLOCATE (ALBEDOLU3(LDAS%NCAT))
      ALLOCATE (ALBEDOLU4(LDAS%NCAT))
      ALLOCATE (ALBEDOLU5(LDAS%NCAT))
      ALLOCATE (ALBEDOLU6(LDAS%NCAT))
      ALLOCATE (ALBEDOLU7(LDAS%NCAT))
      ALLOCATE (ALBEDOLU8(LDAS%NCAT))
      ALLOCATE (ALBEDOLU9(LDAS%NCAT))
      ALLOCATE (ALBEDOLU10(LDAS%NCAT))
      ALLOCATE (ALBEDOLU11(LDAS%NCAT))
      ALLOCATE (ALBEDOLU12(LDAS%NCAT))
      ALLOCATE (VGDLU1(LDAS%NCAT))
      ALLOCATE (VGDLU2(LDAS%NCAT))
      ALLOCATE (VGDLU3(LDAS%NCAT))
      ALLOCATE (VGDLU4(LDAS%NCAT))
      ALLOCATE (VGDLU5(LDAS%NCAT))
      ALLOCATE (VGDLU6(LDAS%NCAT))
      ALLOCATE (VGDLU7(LDAS%NCAT))
      ALLOCATE (VGDLU8(LDAS%NCAT))
      ALLOCATE (VGDLU9(LDAS%NCAT))
      ALLOCATE (VGDLU10(LDAS%NCAT))
      ALLOCATE (VGDLU11(LDAS%NCAT))
      ALLOCATE (VGDLU12(LDAS%NCAT))

!=== Get Vegetation, Soil and Topographic Parameters for Catchment Model 

      CALL VEGETATION(
     i                LDAS%NCAT,LDAS%CAT_MVFILE,                
     o                GREENLU1,GREENLU2,GREENLU3,GREENLU4,GREENLU5,
     o                GREENLU6,GREENLU7,GREENLU8,GREENLU9,GREENLU10,
     o                GREENLU11,GREENLU12,LAILU1,LAILU2,LAILU3,LAILU4,
     o                LAILU5,LAILU6,LAILU7,LAILU8,LAILU9,LAILU10,
     o                LAILU11,LAILU12,ZOLLU1,ZOLLU2,ZOLLU3,ZOLLU4,
     o                ZOLLU5,ZOLLU6,ZOLLU7,ZOLLU8,ZOLLU9,ZOLLU10,
     o                ZOLLU11,ZOLLU12,ALBEDOLU1,ALBEDOLU2,ALBEDOLU3,
     o                ALBEDOLU4,ALBEDOLU5,ALBEDOLU6,ALBEDOLU7,
     o                ALBEDOLU8,ALBEDOLU9,ALBEDOLU10,ALBEDOLU11,
     o                ALBEDOLU12,VGDLU1,VGDLU2,VGDLU3,VGDLU4,VGDLU5,
     o                VGDLU6,VGDLU7,VGDLU8,VGDLU9,VGDLU10,VGDLU11,
     o                VGDLU12)      
      CALL LAND(
     i          LDAS%CAT_SFILE,LDAS%CAT_VFILE,LDAS%NCAT,         
     o          VEGCLSLU,DPTHLU,POROSLU,BF1LU,BF2LU,BF3LU,ARS1LU,
     o          ARS2LU,ARS3LU,ARA1LU,ARA2LU,ARA3LU,ARA4LU,ARW1LU,
     o          ARW2LU,ARW3LU,ARW4LU,TSA1LU,TSA2LU,TSB1LU,TSB2LU)

!=== Set-up pointer array nff to assign parameters to LDAS domain

      CALL ZOOM_SETUP(
     i                LDAS%CAT_SFILE,VEGCLSLU,                
     o                NCATM,CAT%NFF,CAT%LATT,CAT%LONN)             
      IF (NCATM.NE.LDAS%NCATM) THEN
       WRITE(*,*) 'Number of catchments is',LDAS%NCATM
       WRITE(*,*) 'Number of catchments should be',NCATM
       STOP
      ENDIF

!=== Assign parameters to LDAS domain
      CALL ZVEG(
     i          LDAS%NCATM,CAT%NFF,GREENLU1,GREENLU2,GREENLU3,
     i          GREENLU4,GREENLU5,GREENLU6,GREENLU7,GREENLU8,
     i          GREENLU9,GREENLU10,GREENLU11,GREENLU12,LAILU1,
     i          LAILU2,LAILU3,LAILU4,LAILU5,LAILU6,LAILU7,LAILU8,
     i          LAILU9,LAILU10,LAILU11,LAILU12,ZOLLU1,ZOLLU2,ZOLLU3,
     i          ZOLLU4,ZOLLU5,ZOLLU6,ZOLLU7,ZOLLU8,ZOLLU9,ZOLLU10,
     i          ZOLLU11,ZOLLU12,ALBEDOLU1,ALBEDOLU2,ALBEDOLU3,
     i          ALBEDOLU4,ALBEDOLU5,ALBEDOLU6,ALBEDOLU7,ALBEDOLU8,
     i          ALBEDOLU9,ALBEDOLU10,ALBEDOLU11,ALBEDOLU12,VGDLU1,
     i          VGDLU2,VGDLU3,VGDLU4,VGDLU5,VGDLU6,VGDLU7,VGDLU8,
     i          VGDLU9,VGDLU10,VGDLU11,VGDLU12,
     o          CAT%GREEN(1),CAT%GREEN(2),CAT%GREEN(3),CAT%GREEN(4),
     o          CAT%GREEN(5),CAT%GREEN(6),CAT%GREEN(7),CAT%GREEN(8),
     o          CAT%GREEN(9),CAT%GREEN(10),CAT%GREEN(11),CAT%GREEN(12),
     o          CAT%LAI(1),CAT%LAI(2),CAT%LAI(3),CAT%LAI(4),CAT%LAI(5),
     o          CAT%LAI(6),CAT%LAI(7),CAT%LAI(8),CAT%LAI(9),CAT%LAI(10),
     o          CAT%LAI(11),CAT%LAI(12),CAT%ZOL(1),CAT%ZOL(2),
     o          CAT%ZOL(3),CAT%ZOL(4),CAT%ZOL(5),CAT%ZOL(6),CAT%ZOL(7),
     o          CAT%ZOL(8),CAT%ZOL(9),CAT%ZOL(10),CAT%ZOL(11),
     o          CAT%ZOL(12),CAT%ALBEDO(1),CAT%ALBEDO(2),CAT%ALBEDO(3),
     o          CAT%ALBEDO(4),CAT%ALBEDO(5),CAT%ALBEDO(6),CAT%ALBEDO(7),
     o          CAT%ALBEDO(8),CAT%ALBEDO(9),CAT%ALBEDO(10),
     o          CAT%ALBEDO(11),CAT%ALBEDO(12),CAT%VGD(1),CAT%VGD(2),
     o          CAT%VGD(3),CAT%VGD(4),CAT%VGD(5),CAT%VGD(6),CAT%VGD(7),
     o          CAT%VGD(8),CAT%VGD(9),CAT%VGD(10),CAT%VGD(11),
     o          CAT%VGD(12))

      CALL ZOOM(
     i          LDAS%NCATM,CAT%NFF,TSA1LU,TSA2LU,TSB1LU,TSB2LU,
     i          ARW1LU,ARW2LU,ARW3LU,ARW4LU,ARA1LU,ARA2LU, 
     i          ARA3LU,ARA4LU,ARS1LU,ARS2LU,ARS3LU,BF1LU, 
     i          BF2LU,BF3LU,POROSLU,DPTHLU,VEGCLSLU,       
     o          CAT%TSA(1),CAT%TSA(2),CAT%TSB(1),CAT%TSB(2),
     o          CAT%ARW(1),CAT%ARW(2),CAT%ARW(3),CAT%ARW(4), 
     o          CAT%ARA(1),CAT%ARA(2),CAT%ARA(3),CAT%ARA(4),  
     o          CAT%ARS(1),CAT%ARS(2),CAT%ARS(3),CAT%BF(1),    
     o          CAT%BF(2),CAT%BF(3),CAT%POROS,CAT%WPWET,CAT%BEE,
     o          CAT%ZDPTH(1),CAT%ZDPTH(2),CAT%ZDPTH(3),CAT%CDCR(1), 
     o          CAT%CDCR(2),CAT%PSIS,CAT%COND,CAT%GNU,CAT%VGWMAX,
     o          CAT%VEGCLS)

!=== De-allocate Space to Scratch Variables ==============================

      DEALLOCATE (VEGCLSLU)
      DEALLOCATE (DPTHLU)
      DEALLOCATE (POROSLU)
      DEALLOCATE (BF1LU)
      DEALLOCATE (BF2LU)
      DEALLOCATE (BF3LU)
      DEALLOCATE (ARS1LU)
      DEALLOCATE (ARS2LU)
      DEALLOCATE (ARS3LU)
      DEALLOCATE (ARA1LU)
      DEALLOCATE (ARA2LU)
      DEALLOCATE (ARA3LU)
      DEALLOCATE (ARA4LU)
      DEALLOCATE (ARW1LU)
      DEALLOCATE (ARW2LU)
      DEALLOCATE (ARW3LU)
      DEALLOCATE (ARW4LU)
      DEALLOCATE (TSA1LU)
      DEALLOCATE (TSA2LU)
      DEALLOCATE (TSB1LU)
      DEALLOCATE (TSB2LU)
      DEALLOCATE (GREENLU1)
      DEALLOCATE (GREENLU2)
      DEALLOCATE (GREENLU3)
      DEALLOCATE (GREENLU4)
      DEALLOCATE (GREENLU5)
      DEALLOCATE (GREENLU6)
      DEALLOCATE (GREENLU7)
      DEALLOCATE (GREENLU8)
      DEALLOCATE (GREENLU9)
      DEALLOCATE (GREENLU10)
      DEALLOCATE (GREENLU11)
      DEALLOCATE (GREENLU12)
      DEALLOCATE (LAILU1)
      DEALLOCATE (LAILU2)
      DEALLOCATE (LAILU3)
      DEALLOCATE (LAILU4)
      DEALLOCATE (LAILU5)
      DEALLOCATE (LAILU6)
      DEALLOCATE (LAILU7)
      DEALLOCATE (LAILU8)
      DEALLOCATE (LAILU9)
      DEALLOCATE (LAILU10)
      DEALLOCATE (LAILU11)
      DEALLOCATE (LAILU12)
      DEALLOCATE (ZOLLU1)
      DEALLOCATE (ZOLLU2)
      DEALLOCATE (ZOLLU3)
      DEALLOCATE (ZOLLU4)
      DEALLOCATE (ZOLLU5)
      DEALLOCATE (ZOLLU6)
      DEALLOCATE (ZOLLU7)
      DEALLOCATE (ZOLLU8)
      DEALLOCATE (ZOLLU9)
      DEALLOCATE (ZOLLU10)
      DEALLOCATE (ZOLLU11)
      DEALLOCATE (ZOLLU12)
      DEALLOCATE (VGDLU1)
      DEALLOCATE (VGDLU2)
      DEALLOCATE (VGDLU3)
      DEALLOCATE (VGDLU4)
      DEALLOCATE (VGDLU5)
      DEALLOCATE (VGDLU6)
      DEALLOCATE (VGDLU7)
      DEALLOCATE (VGDLU8)
      DEALLOCATE (VGDLU9)
      DEALLOCATE (VGDLU10)
      DEALLOCATE (VGDLU11)
      DEALLOCATE (VGDLU12)
      DEALLOCATE (ALBEDOLU1)
      DEALLOCATE (ALBEDOLU2)
      DEALLOCATE (ALBEDOLU3)
      DEALLOCATE (ALBEDOLU4)
      DEALLOCATE (ALBEDOLU5)
      DEALLOCATE (ALBEDOLU6)
      DEALLOCATE (ALBEDOLU7)
      DEALLOCATE (ALBEDOLU8)
      DEALLOCATE (ALBEDOLU9)
      DEALLOCATE (ALBEDOLU10)
      DEALLOCATE (ALBEDOLU11)
      DEALLOCATE (ALBEDOLU12)

      RETURN
      END

!=========================================================================

      SUBROUTINE ZVEG(
     i                NCATM,NFF,GREENLU1,GREENLU2,GREENLU3,
     i                GREENLU4,GREENLU5,GREENLU6,GREENLU7,GREENLU8,
     i                GREENLU9,GREENLU10,GREENLU11,GREENLU12,LAILU1,
     i                LAILU2,LAILU3,LAILU4,LAILU5,LAILU6,LAILU7,LAILU8,
     i                LAILU9,LAILU10,LAILU11,LAILU12,ZOLLU1,ZOLLU2,
     i                ZOLLU3,ZOLLU4,ZOLLU5,ZOLLU6,ZOLLU7,ZOLLU8,ZOLLU9,
     i                ZOLLU10,ZOLLU11,ZOLLU12,ALBEDOLU1,ALBEDOLU2,
     i                ALBEDOLU3,ALBEDOLU4,ALBEDOLU5,ALBEDOLU6,ALBEDOLU7,
     i                ALBEDOLU8,ALBEDOLU9,ALBEDOLU10,ALBEDOLU11,
     i                ALBEDOLU12,VGDLU1,VGDLU2,VGDLU3,VGDLU4,VGDLU5,
     i                VGDLU6,VGDLU7,VGDLU8,VGDLU9,VGDLU10,VGDLU11,
     i                VGDLU12,
     o                GREEN1,GREEN2,GREEN3,GREEN4,GREEN5,GREEN6,GREEN7,
     o                GREEN8,GREEN9,GREEN10,GREEN11,GREEN12,LAI1,LAI2,
     o                LAI3,LAI4,LAI5,LAI6,LAI7,LAI8,LAI9,LAI10,LAI11,
     o                LAI12,ZOL1,ZOL2,ZOL3,ZOL4,ZOL5,ZOL6,ZOL7,ZOL8,
     o                ZOL9,ZOL10,ZOL11,ZOL12,ALBEDO1,ALBEDO2,ALBEDO3,
     o                ALBEDO4,ALBEDO5,ALBEDO6,ALBEDO7,ALBEDO8,ALBEDO9,
     o                ALBEDO10,ALBEDO11,ALBEDO12,VGD1,VGD2,VGD3,VGD4,
     o                VGD5,VGD6,VGD7,VGD8,VGD9,VGD10,VGD11,VGD12)
c
c Zooms vegetation climatology
c
      IMPLICIT NONE
      INTEGER NCATM,NFF(*)
      REAL GREENLU1(*),GREENLU2(*),GREENLU3(*),GREENLU4(*),GREENLU5(*)
      REAL GREENLU6(*),GREENLU7(*),GREENLU8(*),GREENLU9(*),GREENLU10(*)
      REAL GREENLU11(*),GREENLU12(*),LAILU1(*),LAILU2(*),LAILU3(*)
      REAL LAILU4(*),LAILU5(*),LAILU6(*),LAILU7(*),LAILU8(*),LAILU9(*)
      REAL LAILU10(*),LAILU11(*),LAILU12(*),ZOLLU1(*),ZOLLU2(*)
      REAL ZOLLU3(*),ZOLLU4(*),ZOLLU5(*),ZOLLU6(*),ZOLLU7(*),ZOLLU8(*)
      REAL ZOLLU9(*),ZOLLU10(*),ZOLLU11(*),ZOLLU12(*),ALBEDOLU1(*)
      REAL ALBEDOLU2(*),ALBEDOLU3(*),ALBEDOLU4(*),ALBEDOLU5(*)
      REAL ALBEDOLU6(*),ALBEDOLU7(*),ALBEDOLU8(*),ALBEDOLU9(*)
      REAL ALBEDOLU10(*),ALBEDOLU11(*),ALBEDOLU12(*),VGDLU1(*),VGDLU2(*)
      REAL VGDLU3(*),VGDLU4(*),VGDLU5(*),VGDLU6(*),VGDLU7(*),VGDLU8(*)
      REAL VGDLU9(*),VGDLU10(*),VGDLU11(*),VGDLU12(*),GREEN1(*)
      REAL GREEN2(*),GREEN3(*),GREEN4(*),GREEN5(*),GREEN6(*),GREEN7(*)
      REAL GREEN8(*),GREEN9(*),GREEN10(*),GREEN11(*),GREEN12(*)
      REAL LAI1(*),LAI2(*),LAI3(*),LAI4(*),LAI5(*)
      REAL LAI6(*),LAI7(*),LAI8(*),LAI9(*),LAI10(*),LAI11(*),LAI12(*)
      REAL ZOL1(*),ZOL2(*),ZOL3(*),ZOL4(*),ZOL5(*),ZOL6(*),ZOL7(*)
      REAL ZOL8(*),ZOL9(*),ZOL10(*),ZOL11(*),ZOL12(*),ALBEDO1(*)
      REAL ALBEDO2(*),ALBEDO3(*),ALBEDO4(*),ALBEDO5(*),ALBEDO6(*)
      REAL ALBEDO7(*),ALBEDO8(*),ALBEDO9(*),ALBEDO10(*),ALBEDO11(*)
      REAL ALBEDO12(*),VGD1(*),VGD2(*),VGD3(*),VGD4(*),VGD5(*),VGD6(*)
      REAL VGD7(*),VGD8(*),VGD9(*),VGD10(*),VGD11(*),VGD12(*)

      INTEGER N

      DO N=1,NCATM
       GREEN1(N)=GREENLU1(NFF(N))
       GREEN2(N)=GREENLU2(NFF(N))
       GREEN3(N)=GREENLU3(NFF(N))
       GREEN4(N)=GREENLU4(NFF(N))
       GREEN5(N)=GREENLU5(NFF(N))
       GREEN6(N)=GREENLU6(NFF(N))
       GREEN7(N)=GREENLU7(NFF(N))
       GREEN8(N)=GREENLU8(NFF(N))
       GREEN9(N)=GREENLU9(NFF(N))
       GREEN10(N)=GREENLU10(NFF(N))
       GREEN11(N)=GREENLU11(NFF(N))
       GREEN12(N)=GREENLU12(NFF(N))
       LAI1(N)=LAILU1(NFF(N))
       LAI2(N)=LAILU2(NFF(N))
       LAI3(N)=LAILU3(NFF(N))
       LAI4(N)=LAILU4(NFF(N))
       LAI5(N)=LAILU5(NFF(N))
       LAI6(N)=LAILU6(NFF(N))
       LAI7(N)=LAILU7(NFF(N))
       LAI8(N)=LAILU8(NFF(N))
       LAI9(N)=LAILU9(NFF(N))
       LAI10(N)=LAILU10(NFF(N))
       LAI11(N)=LAILU11(NFF(N))
       LAI12(N)=LAILU12(NFF(N))
       ZOL1(N)=ZOLLU1(NFF(N))
       ZOL2(N)=ZOLLU2(NFF(N))
       ZOL3(N)=ZOLLU3(NFF(N))
       ZOL4(N)=ZOLLU4(NFF(N))
       ZOL5(N)=ZOLLU5(NFF(N))
       ZOL6(N)=ZOLLU6(NFF(N))
       ZOL7(N)=ZOLLU7(NFF(N))
       ZOL8(N)=ZOLLU8(NFF(N))
       ZOL9(N)=ZOLLU9(NFF(N))
       ZOL10(N)=ZOLLU10(NFF(N))
       ZOL11(N)=ZOLLU11(NFF(N))
       ZOL12(N)=ZOLLU12(NFF(N))
       ALBEDO1(N)=ALBEDOLU1(NFF(N))
       ALBEDO2(N)=ALBEDOLU2(NFF(N))
       ALBEDO3(N)=ALBEDOLU3(NFF(N))
       ALBEDO4(N)=ALBEDOLU4(NFF(N))
       ALBEDO5(N)=ALBEDOLU5(NFF(N))
       ALBEDO6(N)=ALBEDOLU6(NFF(N))
       ALBEDO7(N)=ALBEDOLU7(NFF(N))
       ALBEDO8(N)=ALBEDOLU8(NFF(N))
       ALBEDO9(N)=ALBEDOLU9(NFF(N))
       ALBEDO10(N)=ALBEDOLU10(NFF(N))
       ALBEDO11(N)=ALBEDOLU11(NFF(N))
       ALBEDO12(N)=ALBEDOLU12(NFF(N))
       VGD1(N)=VGDLU1(NFF(N))
       VGD2(N)=VGDLU2(NFF(N))
       VGD3(N)=VGDLU3(NFF(N))
       VGD4(N)=VGDLU4(NFF(N))
       VGD5(N)=VGDLU5(NFF(N))
       VGD6(N)=VGDLU6(NFF(N))
       VGD7(N)=VGDLU7(NFF(N))
       VGD8(N)=VGDLU8(NFF(N))
       VGD9(N)=VGDLU9(NFF(N))
       VGD10(N)=VGDLU10(NFF(N))
       VGD11(N)=VGDLU11(NFF(N))
       VGD12(N)=VGDLU12(NFF(N))
      END DO

      RETURN
      END


