      SUBROUTINE GRIBOUT(NX,NY,LDASMASK,HOUR,YESTERDAY,TODAY,STRM)

C***********************************************************************
C  PROGRAM:  GRIBLDAS           WRITE LDAS OUTPUT IN GRIB FORMAT
C  PRGMMR:  MARSHALL & LOHMANN  ORG:  W/NP20
C
C  ABSTRACT:  TAKES HOURLY OUTPUT FILES FROM LDAS MODELS (IN BINARY
C             FORMAT - BIG ENDIAN) AND MAKES GRIB RECORDS FOR ALL FIELDS
C             IN THE FILE.  NOTE ORDER OF FIELDS IN EACH BINARY FILE
C             MUST CORRESPOND TO ORDER OF FIELDS IN KPDS.tbl.  TIME
C             STAMP INFORMATION MUST ALSO APPEAR (YYYYMMDDHH) IN THE
C             TITLE OF EACH BINARY HOURLY OUTPUT FILE.  THIS INFO IS
C             USED IN CONSTRUCTING THE TIME-RELATED PDS OCTETS WHICH
C             DO NOT APPEAR IN KPDS.tbl   
C
C  PROGRAM HISTORY LOG:
C  00-10-15 MARSHALL ORIGINAL TEMPLATE FOR NOAH MODEL
C  00-11-01 LOHMANN  FINALIZED AND CHANGED TO SUBROUTINE
C  01-06-02 LOHMANN  ADDED OUTPUT VARIABLES FOR LDAS
C  13-07-25 XIA      MODIFIED FOR STREAMFLOW OUTPUT
C  13-11-06 XIA      MODIFIED FOR GRIB2 OUTPUT 
C***********************************************************************

      IMPLICIT NONE

      INTEGER NX
      INTEGER NY

      CHARACTER*8 YESTERDAY, TODAY

      LOGICAL*1   LDASMASK(NX,NY)

      REAL    STRM(NX,NY) 

      INTEGER HOUR, HOUR1

      INTEGER KPDS(13)
      INTEGER LUGB, I, J, K, N, IRET, NLDAS, IG, JRET, NFIELDS

      CHARACTER CENT*2, CHOUR*2, GDS(400), GRIBFILE*256
      CHARACTER*12 VANAM


C     read past header info in KPDS.tbl
      OPEN (UNIT = 30, FILE = 'KPDS.tbl') 
      DO K = 1, 42
         READ(30,*)
      END DO
    
C     MAKE OUTPUT FILENAME
C     OUTPUT 0-23Z STREAMFLOW DATA
      HOUR1=HOUR
      WRITE (CHOUR, '(i2.2)') HOUR1
      GRIBFILE = TODAY//CHOUR//'.STRM.grb'//char(0)
      
C     OPEN GRIB FILE

      LUGB = 40
      CALL BAOPEN(LUGB, GRIBFILE, IRET) 
C     WRITE EACH FIELD (IN GRIB) TO HOURLY OUTPUT FIELD
 15   FORMAT (29x, 7I6) 

      NLDAS = NX * NY

      READ (30,*) VANAM, (KPDS(I),I=1,13)
      CALL grib2_wrt_g2func(LDASMASK,HOUR,YESTERDAY,TODAY,
     +     STRM,KPDS,LUGB,IRET)
       
CYX      CALL PUTGB(LUGB,NLDAS,KPDS,KGDS,LDASMASK,STRM,IRET)
      
      IF (IRET .NE. 0) THEN
         PRINT*, 'PUTGB FAILED FOR HOUR = ',HOUR,',','FIELD = STRM'
CJZ  Added Error Checking
         CALL ERREXIT(IRET)
         STOP
      ELSE
         PRINT*, 'wrote STRM'
      END IF
       
      CALL BACLOSE (LUGB, JRET)
      CLOSE (30)

      END
