#!/bin/ksh
date
export PS4='$SECONDS + '
set -x

#############################################################
# NOTE: This job depends on the prod_util module being loaded
#############################################################

#####################################################################################
# Run config file to get input parameters
# NOTE: $nldas_ver must be exported by the submission script prior to running this job (in run_all of lsf directory)!
# This config file should define the following variables
# DATA_IN: Location of working directory, default to /tmpnwprd
# DEV_ECF: If the job is to be running using SMS, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
# SENDECF: Flag Events on ecFlow
# SENDCOM: Copy Files From $TMPDIR to $COMOUT
# SENDDBN: Issue DBNet Client Calls
#####################################################################################
if [ "$RUN_ENVIR" != "nco" ]      ### For Developers
then
  userid=${LOGNAME:?}
  export HOMEnldas=${HOMEnldas:-/gpfs/dell2/emc/modeling/noscrub/$userid/nldas.${nldas_ver:?}}
  PARA_CONFIG=${nldas_para_config:-$HOMEnldas/user/nldas_para_config}
  if [ -s $PARA_CONFIG ] ; then . $PARA_CONFIG ; fi
  export userid=$LOGNAME
  export DATA_IN=${DATA_IN:-/gpfs/dell2/ptmp/$userid/tmpnwprd}
  export SENDECF=${SENDECF:-NO}
  export SENDDBN=${SENDDBN:-NO}
  export SENDCOM=${SENDCOM:-YES}
  export jobid="LL${job}_${envir}.o$$"
  export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${jobid}}
fi

########################################################
# obtain unique process id and make temp directory
########################################################
export DATA_IN=${DATA_IN:-${DATAROOT:?}}
export DATA=$DATA_IN/${jobid:?}
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z

##########################
# Specify NET and RUN Name
##########################
export NET=${NET:-nldas}
export RUN=${RUN:-nldas}

###########################
# Define alert_type
###########################
if [ $RUN_ENVIR = prod -a $envir != prod ]; then
  export alert_type=NLDAS_GB2_PARA
fi

export alert_type=${alert_type:-NLDAS_GB2}

export pgmout="OUTPUT.$$"

####################################
# Specify Execution Areas
####################################
export FIXnldas=${FIXnldas:-$HOMEnldas/fix}
export PARMnldas=${PARMnldas:-$HOMEnldas/parm}
export EXECnldas=${EXECnldas:-$HOMEnldas/exec}
export USHnldas=${USHnldas:-$HOMEnldas/ush}

##############################
# Run setpdy and initialize PDY variables
##############################
setpdy.sh
. ./PDY

##############################################
# Define COM directories
##############################################

if [ "$RUN_ENVIR" = "nco" ] ### For nco operation
then
export COM_IN=${COM_IN:-${COMROOT:?}/${NET}/${envir}}
export COM_OUT=${COM_OUT:-${COMROOT}/${NET}/${envir}}

export COMIN=$COM_IN/nldas.${PDY}
export COMOUT=$COM_OUT/nldas.${PDY}
export COMOUTp1=$COM_OUT/nldas.${PDYp1}

export LOGDIR=${LOGDIR:-${COMROOT}/${NET}/${envir}/logdir}

mkdir -m 775 -p $COMOUT $COMOUTp1 $LOGDIR

# set cpc gauge and cmorph precip directory
export DCOM_IN=${DCOM_IN:-${DCOMROOT:?}/us007003}

# set hourly stage2 precip directory
export COMINpcpanl=${COMINpcpanl:-$(compath.py pcpanl/prod)}

# set rcdas forcing directory
export COMINrcdas=${COMINrcdas:-$(compath.py rcdas/prod)}

env
fi
#############################################################
# execute the script
${PREPSH:-$HOMEnldas/scripts/exnldas_prep.sh.ecf}

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
##if [ "$KEEPDATA" != "YES" ]; then rm -rf $DATA; fi

date
