      SUBROUTINE READ_INITIAL(NX,NY,NSOLD,SMC,SNOWCO)

      IMPLICIT NONE

C     READS INITIAL CONDITIONS
      INTEGER I, J, K
      INTEGER NX
      INTEGER NY
      INTEGER NSOLD

      REAL    SMC(NSOLD,NX,NY)
      REAL    SNOWCO(19,NX,NY)

      READ(72) (((SMC(I,J,K),I=1,NSOLD),J=1,NX),K=1,NY)  
      READ(74) (((SNOWCO(I,J,K),I=1,19),J=1,NX),K=1,NY)

      END
