      SUBROUTINE GRIBOUT(NX,NY,LDASMASK,NSOLD,HOUR,YESTERDAY,
     &        TODAY,ARAIN,ASNOW,EVP,PEVPR,SSRUN,BGRUN,SNOM,  
     &        WEASD, SNOD, SOILM,LSOIL,TSOILM,DUMMY,LUGB)

C***********************************************************************
C  PROGRAM:  GRIBLDAS           WRITE LDAS OUTPUT IN GRIB FORMAT
C  PRGMMR:  MARSHALL & LOHMANN  ORG:  W/NP20
C
C  ABSTRACT:  TAKES HOURLY OUTPUT FILES FROM LDAS MODELS (IN BINARY
C             FORMAT - BIG ENDIAN) AND MAKES GRIB RECORDS FOR ALL FIELDS
C             IN THE FILE.  NOTE ORDER OF FIELDS IN EACH BINARY FILE
C             MUST CORRESPOND TO ORDER OF FIELDS IN KPDS.tbl.  TIME
C             STAMP INFORMATION MUST ALSO APPEAR (YYYYMMDDHH) IN THE
C             TITLE OF EACH BINARY HOURLY OUTPUT FILE.  THIS INFO IS
C             USED IN CONSTRUCTING THE TIME-RELATED PDS OCTETS WHICH
C             DO NOT APPEAR IN KPDS.tbl   
C
C  PROGRAM HISTORY LOG:
C  00-10-15 MARSHALL ORIGINAL TEMPLATE FOR NOAH MODEL
C  00-11-01 LOHMANN  FINALIZED AND CHANGED TO SUBROUTINE
C  13-09-26 YOULONG XIA REVISED FOR GRIB2 OUTPUT
C***********************************************************************

      IMPLICIT NONE

      INTEGER NX
      INTEGER NY
      INTEGER NSOLD

      CHARACTER*8 YESTERDAY, TODAY

      REAL    ARAIN(NX,NY)
      REAL    ASNOW(NX,NY)
      REAL    EVP(NX,NY) 
      REAL    PEVPR(NX,NY)
      REAL    SSRUN(NX,NY)
      REAL    BGRUN(NX,NY) 
      REAL    SOILM(NSOLD,NX,NY)
      REAL    TSOILM(NX,NY)
      REAL    LSOIL(NSOLD,NX,NY)
      REAL    SNOM(NX,NY)
      REAL    WEASD(NX,NY)
      REAL    SNOD(NX,NY)

      REAL    DUMMY(NX,NY)
      INTEGER IPTABLE(13)
      INTEGER HOUR, HOUR1

      INTEGER LUGB, I, J, K, N, IRET, NLDAS,IG,NFIELDS

      LOGICAL*1  LDASMASK(NX,NY)

      CHARACTER CENT*2, CHOUR*2, GDS(400), GRIBFILE*256
      CHARACTER*12 VANAM

C     read past header info in KPDS.tbl
      DO K = 1, 42
         READ(80,*)
      END DO

C     MAKE OUTPUT FILENAME
      IF(HOUR.NE.24)THEN
         HOUR1=HOUR
         WRITE (CHOUR, '(i2.2)') HOUR
         GRIBFILE = YESTERDAY//CHOUR//'.SAC.grb'//char(0)
      ELSE
         HOUR1=HOUR-24
         WRITE (CHOUR, '(i2.2)') HOUR1
         GRIBFILE = TODAY//CHOUR//'.SAC.grb'//char(0)
      ENDIF

C     OPEN GRIB FILE
      LUGB = 40
      CALL BAOPEN (LUGB, GRIBFILE, IRET)

      NLDAS = NX * NY

      READ (80,*) VANAM, (IPTABLE(I),I=1,13)
      CALL grib2_wrt_g2func(LDASMASK,HOUR1,YESTERDAY,TODAY,
     +     ARAIN,IPTABLE,LUGB,IRET)
      IF (IRET .NE. 0) THEN
         PRINT*, 'PUTGB FAILED FOR HOUR = ',HOUR,',','FIELD = ARAIN'
         STOP
      END IF

      READ (80,*) VANAM, (IPTABLE(I),I=1,13)
      CALL grib2_wrt_g2func(LDASMASK,HOUR1,YESTERDAY,TODAY,
     +     ASNOW,IPTABLE,LUGB,IRET)
      IF (IRET .NE. 0) THEN
         PRINT*, 'PUTGB FAILED FOR HOUR = ',HOUR,',','FIELD = ASNOW'
         STOP
      END IF

      READ (80,*) VANAM, (IPTABLE(I),I=1,13)
      CALL grib2_wrt_g2func(LDASMASK,HOUR1,YESTERDAY,TODAY,
     +     EVP,IPTABLE,LUGB,IRET)
      IF (IRET .NE. 0) THEN
         PRINT*, 'PUTGB FAILED FOR HOUR = ',HOUR,',','FIELD = EVP'
         STOP
      END IF

      READ (80,*) VANAM, (IPTABLE(I),I=1,13)
      CALL grib2_wrt_g2func(LDASMASK,HOUR1,YESTERDAY,TODAY,
     +     PEVPR,IPTABLE,LUGB,IRET)
      IF (IRET .NE. 0) THEN
         PRINT*, 'PUTGB FAILED FOR HOUR = ',HOUR,',','FIELD = PEVPR'
         STOP
      END IF

      READ (80,*) VANAM, (IPTABLE(I),I=1,13)
      CALL grib2_wrt_g2func(LDASMASK,HOUR1,YESTERDAY,TODAY,
     +     SSRUN,IPTABLE,LUGB,IRET)
      IF (IRET .NE. 0) THEN
         PRINT*, 'PUTGB FAILED FOR HOUR = ',HOUR,',','FIELD = SSRUN'
         STOP
      END IF

      READ (80,*) VANAM, (IPTABLE(I),I=1,13)
      CALL grib2_wrt_g2func(LDASMASK,HOUR1,YESTERDAY,TODAY,
     +     BGRUN,IPTABLE,LUGB,IRET)
      IF (IRET .NE. 0) THEN
         PRINT*, 'PUTGB FAILED FOR HOUR = ',HOUR,',','FIELD = BGRUN'
         STOP
      END IF

      DO N = 1, NSOLD
         DO J = 1,NY
            DO I = 1,NX
               DUMMY(I,J) = SOILM(N,I,J)
            END DO
         END DO
      READ (80,*) VANAM, (IPTABLE(I),I=1,13)
      CALL grib2_wrt_g2func(LDASMASK,HOUR1,YESTERDAY,TODAY,
     +     DUMMY,IPTABLE,LUGB,IRET)
         IF (IRET .NE. 0) THEN
            PRINT*, 'PUTGB FAILED FOR HOUR=',HOUR,',','FIELD = SOILM',N
            STOP
         END IF
      END DO

      READ (80,*) VANAM, (IPTABLE(I),I=1,13)
      CALL grib2_wrt_g2func(LDASMASK,HOUR1,YESTERDAY,TODAY,
     +     TSOILM,IPTABLE,LUGB,IRET)
      IF (IRET .NE. 0) THEN
         PRINT*, 'PUTGB FAILED FOR HOUR = ',HOUR,',','FIELD = TSOILM'
         STOP
      END IF


      READ (80,*) VANAM, (IPTABLE(I),I=1,13)
      CALL grib2_wrt_g2func(LDASMASK,HOUR1,YESTERDAY,TODAY,
     +     SNOM,IPTABLE,LUGB,IRET)
      IF (IRET .NE. 0) THEN
         PRINT*, 'PUTGB FAILED FOR HOUR = ',HOUR,',','FIELD = SNOM'
         STOP
      END IF

      READ (80,*) VANAM, (IPTABLE(I),I=1,13)
      CALL grib2_wrt_g2func(LDASMASK,HOUR1,YESTERDAY,TODAY,
     +     WEASD,IPTABLE,LUGB,IRET)
      IF (IRET .NE. 0) THEN
         PRINT*, 'PUTGB FAILED FOR HOUR = ',HOUR,',','FIELD = WEASD'
         STOP
      END IF

      READ (80,*) VANAM, (IPTABLE(I),I=1,13)
      CALL grib2_wrt_g2func(LDASMASK,HOUR1,YESTERDAY,TODAY,
     +     SNOD,IPTABLE,LUGB,IRET)
      IF (IRET .NE. 0) THEN
         PRINT*, 'PUTGB FAILED FOR HOUR = ',HOUR,',','FIELD = SNOD'
         STOP
      END IF

      CLOSE (80)

      END
