      INTEGER LUGB

      INTEGER NX
      INTEGER NY
      INTEGER NSOLD
      INTEGER NMONTH
      INTEGER NHOUR
      PARAMETER (NX = 464)
      PARAMETER (NY = 224)
      PARAMETER (NSOLD = 6)
      PARAMETER (NMONTH = 12)
      PARAMETER (NHOUR  = 25)

      REAL    TFREEZ
      PARAMETER (TFREEZ = 273.15)

      INTEGER INOAHETP
      REAL    RH
      REAL    ET_PENMAN

      INTEGER NSOIL(NX,NY)
      INTEGER SOILTYP(NX,NY)
      INTEGER VEGTYP(NX,NY)
      INTEGER SLOPETYP(NX,NY)
      INTEGER LAND_SEA(NX,NY)

      REAL    SOILDEPTH(NSOLD,NX,NY)
      REAL    SMC(NSOLD,NX,NY)
      REAL    SH2O(NSOLD,NX,NY)
      REAL    ALBEDO(NMONTH,NX,NY)
      REAL    SHDFAC(NMONTH,NX,NY)
      REAL    PECLIM(NMONTH,NX,NY)
      REAL    PEADJ(NMONTH,NX,NY)
      REAL    PEADJ_D(NX,NY)
      REAL    TBOT(NX,NY)
      REAL    T1(NX,NY)
      REAL    CMC(NX,NY)
      REAL    SNOWCO(19,NX,NY)

      REAL SMCWLT
      REAL SMCDRY
      REAL SMCREF
      REAL SMCMAX

      CHARACTER*100 CNTRFL
      CHARACTER*150 FILENAME, DIREC
      CHARACTER*2   HOUR_CH
      CHARACTER*8   YESTERDAY, TODAY
      INTEGER       LENGTH
      INTEGER       JULDAY

      REAL    W1
      REAL    W2

      INTEGER M1
      INTEGER M2
      INTEGER ICE
      INTEGER NT
      INTEGER I
      INTEGER J
      INTEGER K

      REAL    DT
      REAL    Z
      REAL    SNOALB

      REAL    SFCSPD
      REAL    PTU
      REAL    CH(NX,NY)
      REAL    ALBEDO_D(NX,NY)
      REAL    SHDFAC_D(NX,NY)
      REAL    PECLIM_D(NX,NY)

      INTEGER   NLDAS
      PARAMETER (NLDAS = NX*NY)
      REAL      F(NX,NY)
      REAL      TAIR(NX,NY,NHOUR)
      REAL      SPFH(NX,NY,NHOUR)
      REAL      PSFC(NX,NY,NHOUR)
      REAL      UWIND(NX,NY,NHOUR)
      REAL      VWIND(NX,NY,NHOUR)
      REAL      EDASSWRD(NX,NY)
      REAL      LWDN(NX,NY,NHOUR)
      REAL      EDASPREC(NX,NY)
      REAL      CONVPREC(NX,NY)
      REAL      CAPE(NX,NY)
      REAL      PEVAP(NX,NY)
      REAL      SOLDN(NX,NY,NHOUR)
      REAL      SKIN(NX,NY)
      REAL      PRCP(NX,NY,NHOUR)
      LOGICAL*1 LB(NX,NY)
      LOGICAL*1 LDASMASK(NX,NY)
      REAL      PRCP_MASK(NX,NY)
      REAL      PAR(NX,NY)
      REAL      ELEV_2d(NX,NY)
      REAL      PERATIO(NX,NY)

      REAL      DT_TAIR
      REAL      DT_SPFH
      REAL      DT_PSFC
      REAL      DT_UWIND
      REAL      DT_VWIND
      REAL      DT_LWDN
      REAL      DT_SOLDN
      REAL      DT_PRCP
      REAL      DT_SPFH_SAT
      REAL      DQSDT2
      REAL      DQSDT
      REAL      TH2

      REAL      ETP(NX,NY)
      REAL      ETA(NX,NY)
      REAL      H(NX,NY)
      REAL      S(NX,NY)
      REAL      RUNOFF1(NX,NY)
      REAL      RUNOFF2(NX,NY)
      REAL      Q1(NX,NY)
      REAL      SNMAX(NX,NY)
      REAL      SOILM(NX,NY)
      REAL      SOILW(NX,NY)
      REAL      ALBSNO(NX,NY)
      REAL      SNOWMELT(NX,NY)
      REAL      FROZEN_PREC(NX,NY)
      REAL      LIQUID_PREC(NX,NY)
      REAL      DUMMY(NX,NY)
      REAL      SNEQV(NX,NY)
      REAL      SNOWH(NX,NY)
      REAL      TPREV(NX,NY)

C     SAC PARAMETERS 2D
      REAL  UZTWM_2d(NX,NY),UZFWM_2d(NX,NY),UZK_2d(NX,NY),
     &      PCTIM_2d(NX,NY),ADIMP_2d(NX,NY),RIVA_2d(NX,NY),
     &      ZPERC_2d(NX,NY),REXP_2d(NX,NY),LZTWM_2d(NX,NY),
     &      LZPK_2d(NX,NY),PFREE_2d(NX,NY),SIDE_2d(NX,NY), 
     &      LZFSM_2d(NX,NY),LZFPM_2d(NX,NY),LZSK_2d(NX,NY),
     &      RSERV_2d(NX,NY)

C     SNOW17 PARAMETERS
      REAL SCF_2d(NX,NY),MFMAX_2d(NX,NY),MFMIN_2d(NX,NY),UADJ_2d(NX,NY),
     &     SI_2d(NX,NY),NMF_2d(NX,NY),TIPM_2d(NX,NY),MBASE_2d(NX,NY),
     &     PXTEMP_2d(NX,NY),PLWHC_2d(NX,NY),DAYGM_2d(NX,NY)
      REAL ADC_2d(11,NX,NY)

C     SAC PARAMETERS 1D
      REAL  UZTWM,UZFWM,UZK,PCTIM,ADIMP,RIVA,ZPERC,REXP,
     &      LZTWM,LZFSM,LZFPM,LZSK,LZPK,PFREE,SIDE,RSERV
C     SAC State variables
      REAL  UZTWC,UZFWC,LZTWC,LZFSC,LZFPC,ADIMC

C     SNOW17 PARAMETERS
      REAL ALAT,SCF,MFMAX,MFMIN,UADJ,SI,NMF,TIPM,MBASE,PXTEMP,PLWHC
      REAL DAYGM,ELEV,PA,ADC(11)
C     SNOW17 STATE VARIABLES
	  REAL CS(19)

C     ETA EVAPOTRANSPIRATION
      REAL NOAHETP(NX,NY,24),ZEN,ZENAVG,DAYLIGHT,XLAT
	  
      CHARACTER*4 CYR
      CHARACTER*2 CMO,CDA
      CHARACTER*11 ENVVAR, ENVVAR2

      INTEGER IYEAR, IMON, IDAY, IDTS, IDT, IDA, IT
      INTEGER ISNOW

      REAL TMP, RAIM, SNOW, EDMND, QS, QG, Q, EVP, PCP
      REAL PAREA
