! SUBROUTINE TO CONVERT DATE INTEGERS INTO STRINGS
        SUBROUTINE INT_TO_STRING( INTVAL, S )

	IMPLICIT NONE

	CHARACTER C
	INTEGER I
	INTEGER IDIG
	INTEGER IHI
	INTEGER ILO
	INTEGER INTVAL
	INTEGER IPOS
	INTEGER IVAL
	CHARACTER ( LEN = * ) S

	S = ' '

	ILO = 1
	IHI = LEN ( S )

	! CHECK IF STRING IS NULL
	IF( IHI <= 0 ) THEN
	   RETURN
	ENDIF

	! MAKE A COPY OF THE INTEGER
	IVAL = INTVAL

	! DO NOT ACCEPT NEGATIVE INTS
	IF( IVAL < 0 ) THEN
	   RETURN
	END IF

	! ABS VALUE OF THE INTEGER GOES INTO S(ILO:IHI).
	IPOS = IHI

	! FIND LAST DIGIT OF IVAL, STRIP IT OFF AND STICK IT INTO STRING
	DO

	   IDIG = MOD ( IVAL, 10 )
	   IVAL = IVAL / 10

	   IF( IPOS < ILO ) THEN
   	   DO I = 1, IHI
   	     S(I:I) = '*'
 	     END DO
	      RETURN
	   END IF

	   CALL DIGIT_TO_CHAR ( IDIG, C )

	   S(IPOS:IPOS) = C
	   IPOS = IPOS - 1

	   ! IF REACHED LAST DIGIT EXIT
	   IF( IVAL == 0 ) THEN
	      EXIT
	   END IF

	END DO

	! TURN LEADING BLANKS INTO ZEROS
	DO I=1,IHI
	   IF( S(1:1) == ' ' ) S(1:1)='0'
	ENDDO

	RETURN

	END

	! SUBROUTINE TO CONVERT INTEGER DIGIT TO CHARACTERS
	SUBROUTINE DIGIT_TO_CHAR ( DIGIT, C )

	IMPLICIT NONE

	CHARACTER C
	INTEGER DIGIT

	! IF INTEGER IS INDEED A SINGLE DIGIT, CONVERT
	IF ( 0 <= DIGIT .AND. DIGIT <= 9 ) THEN
	   C = CHAR ( DIGIT + 48 )
	ELSE
	   C = '*'
	END IF
 
	RETURN

	END

