#!/bin/sh
# Script to recompile the GRIB library and related programs
# Define the GRIB_ENV variable before running this install script
# Verify $GRIB_ENV/config.os before running this script.
#
# To invoke script, at your Unix prompt inside directory $GRIB_ENV,
# type one of the following:   
#	Install sun_acc <cr>
#	Install sun_gcc <cr>
#	Install v5d_sgi_cc <cr>		compiles with vis5d extension
#	Install sgi_cc 	<cr>
############################################################################

if [ "$GRIB_ENV" != `pwd` ]; then
   echo "*** error ***"
   echo " $0 only runs if when variable GRIB_ENV is set to curr dir."
   echo " Setting new environment variables in your login file will not take "
   echo " effect until either you re-login or re-source your login file."
   echo " Check with your System Administrator."
   echo ""
   exit
fi

# Make sure selected Operating System is 1 of the ones in OS Configuration file
# Note:
# If you created a new OS config in 'config.os' then you must add
# the new Target name on the 'for os in ...' line 
#
match=0;
for os in     sgi_cc v5d_sgi_cc sun_acc sun_gcc linux_gcc
do
   if [ "$1" = $os ]; then match=1; fi
done

# If none/invalid OS entered, print correct usage & leave
if [ $# -ne 1 -o $match -eq 0 ]; then cd libsrc;make; exit; fi


# make sure script is invoked from the right place
if [ `ls . 2>&- | grep libsrc    | wc -l` = 0  -o 	\
     `ls . 2>&- | grep config    | wc -l` = 0  -o	\
     `ls . 2>&- | grep include   | wc -l` = 0  -o	\
     `ls . 2>&- | grep lib       | wc -l` = 0  -o	\
     `ls . 2>&- | grep src       | wc -l` = 0  -o	\
     `ls . 2>&- | grep run       | wc -l` = 0  -o	\
     `ls . 2>&- | grep bin       | wc -l` = 0  -o	\
     `ls ./src 2>&- | grep gribsimp    | wc -l` = 0 -o \
     `ls ./src 2>&- | grep encoder_ex  | wc -l` = 0 -o \
     `ls ./src 2>&- | grep decoder_ex  | wc -l` = 0 ];
then
   echo "Cannot find some/all of required dirs! "
   echo
   echo "Verify that the following directory structure exists"
   echo "relative to the Install script location:"
   echo "	./bin"
   echo "	./config"
   echo "	./include"
   echo "	./libsrc"
   echo "	./lib"
   echo "	./run"
   echo "	./src"
   echo "	     /decoder_ex"
   echo "	     /encoder_ex"
   echo "	     /getgribieee"
   echo "	     /gribsimp"
   echo
   exit;
fi

# remove old stuff & start over
echo "Remove the old library & executables"
rm -f lib/grib.a bin/decoder_ex bin/encoder_ex1 bin/encoder_ex2 2>&-
rm -f bin/encoder_ex3 bin/getgribieee bin/gribsimp 2>&-


echo "--------------------------------------------------------------"
echo "**** Install libsrc (make $1):"
cd $GRIB_ENV/libsrc; make clobber; make $1
if [ $? -ne 0 ]; then echo "Install:  failed last step, quit now";exit; fi

echo "--------------------------------------------------------------"
echo "**** Install gribsimp (make $1):"
cd $GRIB_ENV/src/gribsimp; make clobber; make $1
if [ $? -ne 0 ]; then echo "Install:  failed last step, quit now";exit; fi

echo
echo "--------------------------------------------------------------"
echo "**** Building getgribieee..."
cd  $GRIB_ENV/src/getgribieee
make clobber;make $1
if [ $? -ne 0 ]; then echo "Install:  failed last step, quit now";exit; fi

echo
echo "--------------------------------------------------------------"
echo "**** Building Encoder examples..."
cd  $GRIB_ENV/src/encoder_ex
make clobber;make $1
if [ $? -ne 0 ]; then echo "Install:  failed last step, quit now";exit; fi
 
echo
echo "--------------------------------------------------------------"
echo "**** Building Decoder examples..."
cd  $GRIB_ENV/src/decoder_ex
make clobber;make $1
if [ $? -ne 0 ]; then echo "Install:  failed last step, quit now";exit; fi
 
echo
echo "--------------------------------------------------------------"
echo "**** Install done, here is listing of your GRIB_ENV/lib & bin:"
ls -l $GRIB_ENV/lib $GRIB_ENV/bin
exit
